import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Cities from '../components/Cities'
import AddCityForm from '../components/AddCityForm'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Been There</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Been There
        </h1>

        <p className={styles.description}>
        A Place To Track Where In The World You Have Been
        </p>

        <Cities/>
        <AddCityForm />
      </main>
    </div>
  )
}
